/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.test3;

public class App {
  public String getGreeting() {
    return "hi~ h,i~";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("하하하하하하하하하하하하하하");
    System.out.println("Hi~ 에이치 아~이!!");
    System.out.println("야옹");
    System.out.println("점심 버거킹");
    System.out.println("저녁 일식");
    System.out.println("bye~ b,y,e~");
    System.out.println("버거킹 군침이 싹 도노~~");
    System.out.println("zzzzzzz");

  }
}
