/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.test3;

public class App {
  public String getGreeting() {
    return "hi~ h,i~";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("점심 버거킹");
    System.out.println("bye~ b,y,e~");
  }
}
